### ISSUE TITLE
TC端同时使用zipkin导致Bean冲突启动失败

### ISSUE THREAD

**Issue by langmnm** [codingapi/tx-lcn#264]
- [x] I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 1. Bug Description
TC的微服务同时使用zipkin，

### 2. Environment:
- JDK version: 1.8
- OS: mac
- TX-LCN version: 5.0.2R
- Others: 
springboot: 2.0.6
springcloud: Finchley.SR2
spring-cloud-starter-zipkin: 5.4.3

### 3. Exception Stacktrace

```
No qualifying bean of type 'com.netflix.hystrix.strategy.concurrency.HystrixConcurrencyStrategy' available: expected single matching bean but found 2: tracingHystrixConcurrencyStrategy,sleuthHystrixConcurrencyStrategy

Field existingConcurrencyStrategy in org.springframework.cloud.netflix.hystrix.security.HystrixSecurityAutoConfiguration required a single bean, but 2 were found:
	- tracingHystrixConcurrencyStrategy: defined in URL [jar:file:/Users/xxx/.m2/repository/com/codingapi/txlcn/txlcn-tracing/5.0.2.RELEASE/txlcn-tracing-5.0.2.RELEASE.jar!/com/codingapi/txlcn/tracing/http/TracingHystrixConcurrencyStrategy.class]
	- sleuthHystrixConcurrencyStrategy: defined by method 'sleuthHystrixConcurrencyStrategy' in class path resource [org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixAutoConfiguration.class]


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

**Comment by langmnm** [comment]
还有一个问题，就是如果TM down了之后，如果down机时长超过一个阈值，再重启，之前已连接成功的TC都不会在连接了。那么就需要重启所有TC才行了，有没有其他办法？

**Comment by ujued** [comment]
可以试试TM集群

**Comment by langmnm** [comment]
集群这个肯定会有的。

**Comment by langmnm** [comment]
那和zipkin这个有没有结果？

**Comment by stardyun** [comment]
为什么新版本又有这个问题了？

**Comment by ngcly** [comment]
这个问题为何被关了，这个问题依然存在啊，还有如果使用了springboot devtools 热部署也会导致数据源报错：
`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tracingFilter' defined in class path resource [org/springframework/cloud/sleuth/instrument/web/TraceWebServletAutoConfiguration.class]: Unsatisfied dependency expressed through method 'tracingFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'httpTracing' defined in class path resource [org/springframework/cloud/sleuth/instrument/web/TraceHttpAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [brave.http.HttpTracing]: Factory method 'httpTracing' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Unsatisfied dependency expressed through method 'healthEndpoint' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthIndicatorRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthIndicatorAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthIndicatorRegistry]: Factory method 'healthIndicatorRegistry' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper: Common causes of this problem include using a final class or a non-visible class; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.IllegalAccessError-->class com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper$$EnhancerBySpringCGLIB$$a4bf95ba cannot access its superclass com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper (com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper$$EnhancerBySpringCGLIB$$a4bf95ba is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @7679a53a; com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper is in unnamed module of loader 'app')`

**Comment by cwm3412638** [comment]
这个问题要怎么解决
